apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-05-02T10:17:20Z"
  generation: 1
  name: openshift-controller-manager
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: ab33706e-90f2-4e17-b1bb-53511c43691f
  resourceVersion: "15319"
  uid: 92322ac2-b2a3-40a1-ba85-5b2dc38b8ef6
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-05-02T10:20:06Z"
    message: All is well
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-05-02T10:34:15Z"
    message: All is well
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-05-02T10:34:15Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-02T10:20:11Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-05-02T10:20:06Z"
    reason: NoData
    status: Unknown
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: openshiftcontrollermanagers
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-controller-manager-operator
    resource: namespaces
  - group: ""
    name: openshift-controller-manager
    resource: namespaces
  - group: ""
    name: openshift-route-controller-manager
    resource: namespaces
  versions:
  - name: operator
    version: 4.18.0-0.nightly-2025-05-01-190912
